runtime: custom
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always

endpoints_api_service:
  # The following values are to be replaced by information from the output of
  # 'gcloud service-management deploy openapi.yaml' command.
  name: echo-api.endpoints.sheetpay-160603.cloud.goog
  config_id: [2017-03-05r0]
